'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import { ArrowRight, Workflow, Globe, Gauge, Megaphone } from 'lucide-react'
import { staggerContainer, fadeInUp } from '@/lib/motion'
import { ScrollReveal } from '@/components/animations'
import Section from '@/components/shared/Section'
import Container from '@/components/shared/Container'
import SectionLabel from '@/components/shared/SectionLabel'
import { pillars } from '@/lib/data/services'

/* ─────────────────────────────────────────────────────────
   Types
───────────────────────────────────────────────────────── */

interface RelatedEntry {
  slug: string
  /** One sentence explaining why this pillar connects to the current page. */
  note: string
}

/* ─────────────────────────────────────────────────────────
   Curated relationships
   Each pillar links to the 2 pillars it most directly amplifies.
───────────────────────────────────────────────────────── */

const relationships: Record<string, RelatedEntry[]> = {
  'growth-systems': [
    {
      slug: 'performance',
      note: 'The systems you build here determine how well every lead generated by paid and organic channels is handled. CRM and follow-up infrastructure is what makes acquisition investment non-leaky.',
    },
    {
      slug: 'digital-platforms',
      note: 'The platform visitors land on shapes what your systems have to work with. A high-converting destination makes every automated sequence and follow-up more effective.',
    },
  ],
  'digital-platforms': [
    {
      slug: 'performance',
      note: 'A high-converting platform makes every pound of paid spend work harder. Funnel architecture built for conversion directly reduces cost-per-acquisition across every channel above it.',
    },
    {
      slug: 'brand-presence',
      note: 'A platform built on strong positioning converts at a category level, not just for one campaign. Brand clarity and digital infrastructure compound each other.',
    },
  ],
  'performance': [
    {
      slug: 'digital-platforms',
      note: 'Every acquisition channel you run depends on the quality of the platform it sends traffic to. The best media strategy stalls against a weak conversion layer.',
    },
    {
      slug: 'growth-systems',
      note: 'Acquisition channels can only perform as well as the systems that receive the leads they generate. CRM and follow-up infrastructure is what makes marketing investment compound.',
    },
  ],
  'brand-presence': [
    {
      slug: 'performance',
      note: 'Strong positioning and content reduce paid CAC over time. Audiences warmed by brand and thought leadership convert at significantly higher rates than cold traffic.',
    },
    {
      slug: 'digital-platforms',
      note: 'A website built on clear positioning converts at a category level. Brand clarity without a platform that expresses it is a substantial underused asset.',
    },
  ],
}

/* ─────────────────────────────────────────────────────────
   Icon map
───────────────────────────────────────────────────────── */

const iconMap = {
  workflow: Workflow,
  globe: Globe,
  gauge: Gauge,
  megaphone: Megaphone,
} as const

/* ─────────────────────────────────────────────────────────
   Component
───────────────────────────────────────────────────────── */

interface RelatedServicesProps {
  currentSlug: string
}

export default function RelatedServices({ currentSlug }: RelatedServicesProps) {
  const related = relationships[currentSlug] ?? []
  if (related.length === 0) return null

  const relatedPillars = related
    .map((entry) => {
      const pillar = pillars.find((p) => p.slug === entry.slug)
      return pillar ? { pillar, note: entry.note } : null
    })
    .filter(Boolean) as Array<{ pillar: (typeof pillars)[number]; note: string }>

  if (relatedPillars.length === 0) return null

  return (
    <Section bg="secondary" id={`related-services-${currentSlug}`}>
      <Container>
        <div className="mb-10">
          <ScrollReveal>
            <SectionLabel withLine className="mb-4">
              How this connects
            </SectionLabel>
          </ScrollReveal>
          <ScrollReveal delay={0.06}>
            <h2 className="font-display text-[clamp(22px,3vw,32px)] font-bold leading-snug tracking-[-0.02em] text-text-primary">
              The infrastructure works better in layers.
            </h2>
          </ScrollReveal>
          <ScrollReveal delay={0.1}>
            <p className="mt-3 max-w-xl font-body text-[14px] leading-relaxed text-text-secondary">
              Each pillar reinforces the others. The services below connect most directly
              to this one — and are often where the next highest-leverage investment sits.
            </p>
          </ScrollReveal>
        </div>

        <motion.div
          variants={staggerContainer(0.1)}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-60px' }}
          className="grid gap-5 sm:grid-cols-2"
        >
          {relatedPillars.map(({ pillar, note }) => {
            const Icon = iconMap[pillar.iconName]
            const gradientStyle = pillar.gradientVia
              ? `linear-gradient(135deg, ${pillar.gradientFrom} 0%, ${pillar.gradientVia} 50%, ${pillar.gradientTo} 100%)`
              : `linear-gradient(135deg, ${pillar.gradientFrom} 0%, ${pillar.gradientTo} 100%)`

            return (
              <motion.div
                key={pillar.id}
                variants={fadeInUp}
                className="group flex flex-col overflow-hidden rounded-2xl border border-border-subtle bg-bg-elevated transition-all duration-300 hover:border-border-hover"
              >
                {/* Gradient top line */}
                <div
                  className="h-[2px] w-full shrink-0"
                  style={{ background: gradientStyle }}
                  aria-hidden="true"
                />

                <div className="flex flex-1 flex-col p-7">
                  {/* Icon + name */}
                  <div className="mb-4 flex items-center gap-3">
                    <div
                      className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl"
                      style={{ background: gradientStyle }}
                      aria-hidden="true"
                    >
                      <Icon size={16} className="text-white" />
                    </div>
                    <div>
                      <p className="font-mono text-[10px] uppercase tracking-[0.1em] text-text-muted">
                        Related pillar
                      </p>
                      <p className="font-display text-[15px] font-semibold tracking-[-0.01em] text-text-primary">
                        {pillar.name}
                      </p>
                    </div>
                  </div>

                  {/* Tagline */}
                  <p
                    className="mb-3 font-display text-[14px] font-semibold leading-snug"
                    style={{
                      backgroundImage: gradientStyle,
                      WebkitBackgroundClip: 'text',
                      WebkitTextFillColor: 'transparent',
                      backgroundClip: 'text',
                    }}
                  >
                    {pillar.tagline}
                  </p>

                  {/* Connection note */}
                  <p className="mb-6 flex-1 font-body text-[13px] leading-relaxed text-text-secondary">
                    {note}
                  </p>

                  {/* Link */}
                  <Link
                    href={`/services/${pillar.slug}`}
                    className="group/link inline-flex items-center gap-1.5 font-body text-[13px] font-medium text-text-muted transition-colors duration-200 hover:text-text-primary focus-visible:outline-none focus-visible:rounded-sm focus-visible:ring-2 focus-visible:ring-accent-primary"
                    aria-label={`Explore ${pillar.name}`}
                  >
                    Explore {pillar.name}
                    <ArrowRight
                      size={13}
                      className="transition-transform duration-200 group-hover/link:translate-x-1"
                      aria-hidden="true"
                    />
                  </Link>
                </div>
              </motion.div>
            )
          })}
        </motion.div>

        {/* Back to all services */}
        <ScrollReveal delay={0.1}>
          <div className="mt-8 flex justify-center">
            <Link
              href="/services"
              className="group inline-flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.12em] text-text-muted transition-colors duration-200 hover:text-text-secondary focus-visible:outline-none focus-visible:rounded-sm focus-visible:ring-2 focus-visible:ring-accent-primary"
            >
              <span
                className="h-px w-5 bg-current transition-all duration-300 group-hover:w-3"
                aria-hidden="true"
              />
              View all services
            </Link>
          </div>
        </ScrollReveal>
      </Container>
    </Section>
  )
}
